name: Debricked scan

on: [push, pull_request]

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install Conan SBOM generator # https://github.com/CycloneDX/cyclonedx-conan
      run: |
          python -m pip install -U conan
          conan profile detect
          conan config install https://github.com/conan-io/conan-extensions.git
          python -m pip install 'cyclonedx-python-lib>=5.0.0,<6'
    - name: Generate Conan SBOM
      run: |
        conan sbom:cyclonedx --help
        conan sbom:cyclonedx --format 1.4_json .
    - uses: debricked/actions@v4
      env:
        DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
